name: shared
description: Shared models and services for survey applications
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.13.6
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2 # form_app と同じバージョン
  firebase_messaging: ^14.7.10
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.3.3
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

dependency_overrides:
  firebase_core_web: 2.10.0
