name: shared
description: Shared models and services for survey applications
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.10.4 <4.0.0' # Flutter 3.38.5

dependencies:
  cloud_firestore: ^5.6.10
  firebase_auth: ^5.6.1
  firebase_core: ^3.15.0 # form_app と同じバージョン
  firebase_messaging: ^15.2.8
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.5.0
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

dependency_overrides:
  firebase_core_web: 2.10.0
