name: shared
description: Shared models and services for survey applications

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.0
  firebase_auth: ^4.17.0
  firebase_messaging: ^14.9.4
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.2.1
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
