name: form_app_monorepo
description: Monorepo for survey applications

environment:
  sdk: '>=3.1.3 <4.0.0'

dev_dependencies:
  melos: ^3.4.0

dependency_overrides:
  firebase_core_web: 2.10.0 # 古いバージョンを強制
