name: form_app_monorepo
description: Monorepo for survey applications

environment:
  sdk: '>=3.10.4 <4.0.0' # Flutter 3.38.5

dev_dependencies:
  melos: ^7.3.0

dependency_overrides:
  firebase_core_web: 2.10.0 # 古いバージョンを強制
