name: form_app
description: Survey application for users
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.10.4 <4.0.0' # Flutter 3.38.5

dependencies:
  firebase_core: ^3.15.0 # shared と同じバージョン
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.1.0
  go_router: ^17.0.1
  provider: ^6.1.1
  shared:
    path: ../../packages/shared
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
