name: form_app
description: Survey application for users
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  firebase_core: ^2.24.2 # shared と同じバージョン
  fl_chart: ^0.64.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.0
  provider: ^6.1.1
  shared:
    path: ../../packages/shared

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
